### ISSUE TITLE
Criar página de relatório das sessões por filme

### ISSUE THREAD

**Issue by lpirola** [TaturanaMobi/plataforma-frontend#23]
Criar uma listagem de sessões por filme com uma a seguinte estrutura:

**Filme: [titulo do relatorio/ geral]**

**Data da exibição: [data e hora]**
**Local: nome do espaço e endereço - cidade - uf - país**

**Embaixador:** [nome da pessoa]
**email:** xxx@
**telefone:** 9348753485613289

**Número de espectadores esperados:** xx
**Número de espectadores que compareceram:** xx

**Como foi:**
Descrição do evento...

**Fotos:**

[foto 1]

[foto 2]

[foto 3]

__________________________________

**Comment by vivianedias** [comment]
Esse também!

**Comment by lpirola** [comment]
@lfagundes atualizei a issue!

**Comment by lpirola** [comment]
- [x] Remover limite do texto de descrição do relatório

**Comment by lpirola** [comment]
Limite não encontrado na listagem.
